name: 'cosmosproject'
version: '1.0.0'
config-version: 2

profile: 'cosmosproject'

target-path: 'target' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"

vars:
   surrogate_key_treat_nulls_as_empty_strings: True



data_tests:
   +store_failures: true  

models:
  cosmosproject:
    staging:
      materialized: view
      snowflake_warehouse: load_data1
      post-hook:
        - "{{ update(this) }}"
        - "{{ add_and_update_column(this) }}"
    consumption:
      materialized: view
      snowflake_warehouse: load_data1
    marts:
      materialized: table
      snowflake_warehouse: load_data1

